# local database config
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: h2db
    password: h2db
    schema: "classpath:db/schema.sql"
    initialization-mode: always
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      leak-detection-threshold: 30000
      connection-test-query: SELECT 1
    jpa:
      properties:
        org:
          hibernate:
            envers:
              audit_table_suffix: _HISTORY
        hibernate:
          format_sql: true
spring.h2.console.enabled: true
spring.jpa.defer-datasource-initialization: true

# only local enable swagger ui
springdoc:
  version: "0.0.1"
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    display-request-duration: true
    groups-order: ASC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: false
  packages-to-scan: com.github.bccyben.appsvr

# file server(s3)
fileserver:
  storage:
    enabled: false
    public-bucket: 
    product-folder: 
    accessKey: 
    secretKey: 
    endpoint: 

# aws SES
ses:
  enabled: false
  sender: 
  accessKey: 
  secretKey: 
  support: 

# keycloak
keycloak:
  enabled: false
  url:
  # ここで指定するユーザーは、Role Mappings に、Client Roles: realm-management の中 realm-admin ロールを持つ必要がある
  adminRealm:
  username:
  password:
  targetRealm:
  clientId:

spring.servlet.multipart:
  enabled: true
  file-size-threshold: 1MB
  max-file-size: 10MB
  max-request-size: 20MB
  resolve-lazily: true